[package]
name = "lemon_engine"
version = "0.1.1"
edition = "2018"
license = "MIT"
description = "A game engine based off of Glium"
exclude = [
    "game/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.30.1"
